all:
	cat 128p-0.rom \
		128-1.rom \
		../rom_src/rom1.bin \
		ESXMMC.BIN ESXMMC.BIN \
		dvmen3e0.rom \
		dvmen3e1.rom \
		dvmen3e2.rom \
		opense.rom \
		>sizif-512-010.rom
	cat sizif-512-010.rom \
		zxdiag.rom zxdiag.rom zxdiag.rom zxdiag.rom zxdiag.rom zxdiag.rom zxdiag.rom zxdiag.rom \
		>sizif-512-020.rom
	cat sizif-512-020.rom \
		DiagROM.v50 DiagROM.v50 DiagROM.v50 DiagROM.v50 DiagROM.v50 DiagROM.v50 DiagROM.v50 DiagROM.v50 \
		S128_ZX81_ED2_ROM.bin S128_ZX81_ED2_ROM.bin S128_ZX81_ED2_ROM.bin S128_ZX81_ED2_ROM.bin S128_ZX81_ED2_ROM.bin S128_ZX81_ED2_ROM.bin S128_ZX81_ED2_ROM.bin S128_ZX81_ED2_ROM.bin \
		>sizif-512-040.rom
