    MACRO DEFSTR _string
    DB _string,0
@.end:
    ENDM
    DB 0

str_sizif:             DEFSTR "SIZIF-512"
str_pause:             DEFSTR " PAUSE "
str_exit:              DEFSTR "Exit"
str_exit_reboot:       DEFSTR "& reboot     "
str_exit_no_reboot:    DEFSTR "             "
str_on:                DEFSTR "   ON"
str_off:               DEFSTR "      OFF"
str_on_short:          DEFSTR " ON"
str_off_short:         DEFSTR "OFF"
str_machine:           DEFSTR "Machine"
str_machine_48:        DEFSTR "      48"
str_machine_128:       DEFSTR "     128"
str_machine_3e:        DEFSTR "     +3e"
str_machine_pentagon:  DEFSTR "Pentagon"
str_cpu:               DEFSTR "CPU freq"
str_cpu_35:            DEFSTR "3.5MHz"
str_cpu_44:            DEFSTR "4.4MHz"
str_cpu_52:            DEFSTR "5.2MHz"
str_cpu_7:             DEFSTR "  7MHz"
str_cpu_14:            DEFSTR " 14MHz"
str_panning:           DEFSTR "Panning"
str_panning_abc:       DEFSTR " ABC"
str_panning_acb:       DEFSTR " ACB"
str_panning_mono:      DEFSTR "Mono"
str_joystick:          DEFSTR "Joystick"
str_joystick_kempston: DEFSTR "Kempston"
str_joystick_sinclair: DEFSTR "Sinclair"
str_rom48:             DEFSTR "48K ROM"
str_rom48_default:     DEFSTR "Default"
str_rom48_lg:          DEFSTR "     LG"
str_rom48_opense:      DEFSTR " OpenSE"
str_sd:                DEFSTR "SD card"
str_divmmc:            DEFSTR "DivMMC"
str_zc3e:              DEFSTR "ZC/+3e"
str_ulaplus:           DEFSTR "ULA+"
str_dac:               DEFSTR "DAC"
str_dac_covox:         DEFSTR "   Covox"
str_dac_sd:            DEFSTR "      SD"
str_dac_covoxsd:       DEFSTR "Covox+SD"
str_tsfm:              DEFSTR "TSFM+MIDI"
str_saa:               DEFSTR "SAA1099"
str_gs:                DEFSTR "GS"
str_menuadv:           DEFSTR "Advanced..."
str_sd_indication:     DEFSTR "SD indication"
str_bright_boost:      DEFSTR "Bright boost"
str_autoturbo:         DEFSTR "Auto CPU freq"
str_zxkit1:            DEFSTR "ZXKit1"
str_joy_a_up:          DEFSTR "Map joy A as UP"
str_save_settings:     DEFSTR "Save settings"
str_error:             DEFSTR "ERROR"
str_no_error:          DEFSTR "     "
str_back:              DEFSTR "Go back..."
str_normal_boot:       DEFSTR "Normal boot"
str_zx80:              DEFSTR "ZX80"
str_zx81:              DEFSTR "ZX81"
str_negluk:            DEFSTR "HE GLUK"
